---
output:
  md_document:
    variant: markdown_github
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

MapMark4 is a software package that implements the probability calculations in three-part mineral resource assessments. The name is derived from the descriptive phrase “mineral assessment program mark4”—the name “mark4” is chosen because the previous, similar program was called “mark3”. Functions within the software package are written in the R statistical programming language, which is called either “R language” or “R” in this user’s guide. These functions, their documentation, are bundled together in R’s unit of sharable code, which is called a “package.” MapMark4 provides the essential R functions to perform the probability calculations but does not provide a graphical user’s interface.

If you are interested in obtaining the source code for the package, then it can be downloaded from this GIT repository. However, if you only want to use the package, then you can obtain the installation files (as well as the user’s guide formatted as a USGS publication) from  https://pubs.er.usgs.gov/publication/tm7C14. 

Disclaimer
This software is in the public domain because it contains materials that originally came from the U.S. Geological Survey, an agency of the United States Department of Interior. For more information, see the official USGS copyright policy at http://www.usgs.gov/visual-id/credit_usgs.html#copyright

Although this software program has been used by the U.S. Geological Survey (USGS), no warranty, expressed or implied, is made by the USGS or the U.S. Government as to the accuracy and functioning of the program and related program material nor shall the fact of distribution constitute any such warranty, and no responsibility is assumed by the USGS in connection therewith.

This software is provided "AS IS."

<!-- README.md is generated from README.Rmd. Please edit that file -->


